# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3.9

exclude: '^examples/'

repos:
-   repo: local
    hooks:
      - id: refactor
        name: refactor
        language: system
        entry: refactor
        types: [python]
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--experimental-string-processing]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      -  id: mypy
         args:
         -   --disallow-incomplete-defs
         -   --ignore-missing-imports
         -   --disable-error-code
         -   attr-defined
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.8.3
    hooks:
      - id: unimport
        args:
        -   --remove
        -   --ignore-init
-   repo: https://github.com/executablebooks/mdformat/
    rev: 0.7.5
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat_tables
        - mdformat-black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
